# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Pong_config = debug

else ifeq ($(config),release)
  Pong_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Pong

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Pong:
ifneq (,$(Pong_config))
	@echo "==== Building Pong ($(Pong_config)) ===="
	@${MAKE} --no-print-directory -C . -f Pong.make config=$(Pong_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Pong.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Pong"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"